---
title: "data_wrangling_i"
author: "Blair Wigsten"
date: "9/17/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

#never uuse absolute paths, always use relative paths#

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

```{r}
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
pups_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
pups_data = janitor::clean_names(pups_data)
pups_data

tail(pups_data)
skimr::skim(litters_data)
```

#play with column parsing#
```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
col_types = cols(
  Group = col_character(),
  `Litter Number` = col_character(),
  `GD0 weight` = col_double(),
  `GD18 weight` = col_double(),
  `GD of Birth` = col_double(),
  `Pups born alive` = col_double(),
  `Pups dead @ birth` = col_double(),
  `Pups survive` = col_double()
)
```

#read in excel file

```{r}
mlb11_data_import_examples = read_excel(path = "./data_import_examples/mlb11.xlsx")
```

#read in SAS

```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")
```

